### ISSUE TITLE
Lastest doc is not published

### ISSUE THREAD

**Issue by s-celles** [bkamins/EventSimulation.jl#8]
Hello,

I noticed watching at

https://bkamins.github.io/EventSimulation.jl/latest/tutorial/

the use of

    srand(1)

but it doesn't exists anymore in Julia 1.6.

Fortunately, you fixed it 2 years ago...

https://github.com/bkamins/EventSimulation.jl/commit/32b1ca2dab786a0c256f88a70ecf324928f07b0c

but latest doc doesn't seems to have been published correctly.

Kind regards

PS : same problem also occurs with https://bkamins.github.io/EventSimulation.jl/stable/tutorial/

**Comment by bkamins** [comment]
fixed
